# Generated by Django 5.0.1 on 2024-02-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerall',
            name='user_id',
            field=models.TextField(db_collation='utf8_bin'),
        ),
    ]
