# Generated by Django 5.0.1 on 2024-02-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0002_alter_registerall_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerall',
            name='pwd',
            field=models.TextField(db_collation='utf8_bin'),
        ),
    ]
