# Generated by Django 5.0.1 on 2024-03-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0003_alter_registerall_pwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerall',
            name='rejoin_dt',
            field=models.DateField(default='0001-01-01'),
        ),
        migrations.AddField(
            model_name='registerall',
            name='reliving_dt',
            field=models.DateField(default='0001-01-01'),
        ),
    ]
