# Generated by Django 5.0.1 on 2024-03-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0006_addloan'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddClockin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usid', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('branch', models.TextField()),
            ],
            options={
                'db_table': 'app_clockin',
            },
        ),
    ]
